baseURL = "https://rafed.github.io/ramium/"
# CanonifyURLs=true
# npm install postcss-cli purgecss

languageCode = "en-us"
theme = "ramium"

title = "Ramium"
disqusShortname = "rafed"
googleAnalytics = "UA-106132552-1"
pluralizeListTitles = false
enableemoji = false

[params]
    description = "A description for the meta tag of the site"
    leanCSS = false # make true for leaner css (requires npm installs, see docs)
    googleSearch = "000151824860492892407:kd5zijxwj6a"
    adsense = "ca-pub-7125931910131040"
    showDate = true # make false if dont want to show date for evergeen articles
    math = false # best to enable this in the front matter of a page
    githubProfile = "rafed/ramium/"

    tagsInHome = 40     # set zero to not show in home page
    sectionsInHome = 5  # set zero to not show in home page
    paginatePostsPerPage = 5
    paginateTagsPerPage = 6

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true
